baseURL = 'https://username.github.io/reddawn/'
languageCode = 'ru-ru'
title = 'Red Dawn'
disableKinds = ['taxonomy', 'term']

[pagination]
  pagerSize = 6

[params]
  description = 'Московская страйкбольная команда Red Dawn'
  keywords = ['страйкбольная команда', 'Московская страйкбольная команда', 'страйкбол', 'Red Dawn', 'команда', 'airsoft']
  author = 'Chief'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Настройки для GitHub Pages
publishDir = 'public'
